### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by cwensley** [clicketyclackety/Crash#14]
**Describe the bug**
When there are a lot of objects, deselecting an object makes all other clients hang.  I think this might be due to sending an Unselect for every object in the document vs. just the ones that were selected.

We can do a few things: 
  1. Only call Unselect() on the objects that were selected to begin with
  2. Modify the endpoints so they accept an array of Guids instead of calling the endpoint for each object selected.

**To Reproduce**
  1. Open a shared model with many objects with more than one clients
  2. Select an object
  3. Deselect the object
  4. Notice the hang on all other clients that are connected

**Expected behavior**
Deselecting an object should not hang other clients and should perform quickly.

**Comment by clicketyclackety** [comment]
On large part of this also is that currently we're not caching the geometry of the specks. We're requesting it every time we need it. I'm going to create a PR that starts to cache the geometry, and that should help mitigate this.
