### ISSUE TITLE
Add CI support for yak and azure publishing

### ISSUE THREAD

**Issue by cwensley** [clicketyclackety/Crash#15]
We should add GitHub Actions CI support to easily publish new versions of the yak package and the shared web server.

**Comment by clicketyclackety** [comment]
I think the best way to do this would be a matrix container with a custom powershell script to do the compiling so we don't need to rely on yak. I'll have a go at it. Although I know that Yak is quite finicky about which compression program is used for it.

**Comment by clicketyclackety** [comment]
I eventually realised running it on one Windows container is much easier and has less hassle. But unsure if it's the perfect solution
