### ISSUE TITLE
Closing a model without releasing leaves temporary geometry stranded in the database

### ISSUE THREAD

**Issue by clicketyclackety** [clicketyclackety/Crash#17]
**Describe the bug**
Closing a model without releasing or deleting items leaves temporary items in the server. These items are then effectively released on next open.

**To Reproduce**
1. Start a local server
2. Create some geometry
3. Exit the model without saving or releasing
4. Open a new model
5. Open the local server

**Expected behaviour**
Geometry that was not released should not be added to anyone's documents on reconnect.

**Version Info (please complete the following information):**
 - Rhino Version [7.23.x]
 - Crash Version [1.0.0]

**Additional context**
This bug raises a few questions.
Does Crash keep old geometry as a kind of save state so that users can reconnect and start working on it later?
	This would mean that work in progress geometry in a crash model can be left and picked up on other machines which opens a lot of quite fantastic possibilities.
Or, does Crash delete and dump any temporary geometry when a user disconnects without saving?

If a user were to just leave geometry data stranded in a model it would essentially be clutter until they reconnected and deleted it.

**Comment by clicketyclackety** [comment]
I'd love your take on this @cwensley 😊

**Comment by cwensley** [comment]
I think the end goal should be to persist all of the temporary geometry ideally so someone can reconnect and start off where they were before.

I think what's going wrong here is that when you connect the OnInitialize is baking everything instead of looking at the Temporary and Owner properties and place those in the local dictionaries to render them via the display conduit.

**Comment by clicketyclackety** [comment]
Thanks @cwensley . What you've said makes a lot of sense. It seems it'd be easier and better on Initialise to only bake all released geometry and user specific temporary geometry.

I'll see if I can't include this improvent in the Speck improvement PR.
