### ISSUE TITLE
UnauthorizedAccess : Rhino needs to be ran as admin

### ISSUE THREAD

**Issue by lin-ycv** [clicketyclackety/Crash#32]
If Rhino is not started as admin, the server won't start

**To Reproduce**
1. launch Rhino normal
2. `StartSharedModel`, and fill out info
3.  gets exception and server closes

**Expected behavior**
servers starts up normally

**Screenshots**
![image](https://user-images.githubusercontent.com/60565737/202626877-e8cd24ba-09cc-4eff-8f29-369cbceb41c9.png)

**Version Info (please complete the following information):**
 - Rhino Version 7.24
 - Crash Version 1.0.0

**Additional context**

**Comment by clicketyclackety** [comment]
Thanks for spotting this @lin-ycv, it seems you're using the Yak Package whilst so far we've only debugged locally hence why we haven't seen this 😊. 

This line is responsible for this problem
https://github.com/clicketyclackety/Crash/blob/5b0a69c3c4df91252cf3545053ac6721ef8ef6c7/Crash.Server/Program.cs#L10-L16

I have started a fix in #34

**Comment by clicketyclackety** [comment]
Should be fixed with #33. I will create a new release soon
