### ISSUE TITLE
Release isn't meaningful

### ISSUE THREAD

**Issue by lin-ycv** [clicketyclackety/Crash#33]
**Describe the bug**
When a user releases control over geometry, it doesn't really mean anything, other users still have no real control over their geometry, Geometry owner simply sees a duplicate instead of having the geometry change, and changes to the original geometry will overwrite any previous modifications from all users.

**To Reproduce**
1. User B models a geometry and releases it
2. User A modifies the geometry -> User B see a duplicate
3a. User B modifies original geometry -> changes by user A are discarded
3b. User B modifies the duplicate (released) geometry -> user A see a duplicate
4. User B modifies original geometry -> all duplicates are discarded

**Expected behavior**
2. original geometry should be modified, or there's a setting where user can chose either behaviour
3a. user a geometry should be kept
3b. (same as 2)
4. (same as 3a)  

**Screenshots**
![copy](https://user-images.githubusercontent.com/60565737/202629769-5d9b1730-2cb3-4abb-8e6d-74acee797f9e.gif)

**Version Info (please complete the following information):**
 - Rhino Version 7.24
 - Crash Version 1.0.0

**Additional context**

**Comment by clicketyclackety** [comment]
Hey @lin-ycv. This is part of a weird duplication bug that seems to happen. I will look into it and see if I can repeat it. Thank you so much for reporting this error in such detail 😊

**Comment by clicketyclackety** [comment]
Issue has certainly been resolved by the latest verisons
